### ISSUE TITLE
Morning Session - Peer to peer code-reveiew

### ISSUE THREAD

**Issue by Xghayor** [CVILLA09/Microverse-Portfolio-Project#13]
<h1>Good Job </h1>
1.Everything is done according to the requirements, Great work!.

**Comment by Movgto** [comment]
## **Great work**! it seems there's nothing that needs to be changed!
Only a suggestion about the names of the sections, I think you could include only the name of the section itself and don't include the 'section' part.
This would help to improve reading quality I think, it's not something actually important but that's the only thing I could suggest to change 😅

**Comment by CVILLA09** [comment]
<h1>Great! Thanks for the feedback!</h1>

<img src="https://media0.giphy.com/media/l3q2wJsC23ikJg9xe/giphy-downsized-medium.gif"/>
