### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Xghayor** [CVILLA09/Microverse-Portfolio-Project#15]
<h1>Great work completing this task</h1>
1.Great job on building the popup window dynamically!

**Comment by Movgto** [comment]
You have made an amazing job completing this feature, and there's nothing that needs to be changed I just would highlight how well-detailed is the description for your pull request, it looks very professional good job with everything! 🥳

**Comment by CVILLA09** [comment]
<h1>Thanks for the feedback! </h1>

<img src="https://media0.giphy.com/media/l3q2wJsC23ikJg9xe/giphy-downsized-medium.gif"/>
